network:
  version: 1
  config:
    - type: physical
      name: eth0
      subnets:
        - type: static
          address: 10.244.0.10
          netmask: 255.255.255.0
          gateway: 10.244.0.10
      
    dns_nameservers:
            - 10.244.0.10
          dns_search:
            - its.local