network:
  version: 1
  config:
  - type: physical
    name: eth0
    subnets:
    - type: static
      address: ${node_address}
      netmask: ${node_mask}
      gateway: ${node_gateway}
    dns_nameservers:
     - ${node_dns_address}
    dns_search:
     - ${node_dns_search}